export const GET_PICTURES = "GET_PICTURES";
export const GET_PICTURES_OK = "GET_PICTURES_OK";
export const GET_PICTURES_FAIL = "GET_PICTURES_FAIL";

export const GET_MARS_WEATHER = "GET_MARS_WEATHER";
export const GET_MARS_WEATHER_OK = "GET_MARS_WEATHER_OK";
export const GET_MARS_WEATHER_FAIL = "GET_MARS_WEATHER_FAIL";