export const GET_PICTURE_DAY = "GET_PICTURE_DAY";
export const GET_PICTURE_DAY_OK = "GET_PICTURE_DAY_OK";
export const GET_PICTURE_DAY_FAIL = "GET_PICTURE_DAY_FAIL";

export const GET_MARS_WEATHER = "GET_MARS_WEATHER";
export const GET_MARS_WEATHER_OK = "GET_MARS_WEATHER_OK";
export const GET_MARS_WEATHER_FAIL = "GET_MARS_WEATHER_FAIL";

export const GET_MARS_IMAGES = "GET_MARS_IMAGES";
export const GET_MARS_IMAGES_OK = "GET_MARS_IMAGES_OK";
export const GET_MARS_IMAGES_FAIL = "GET_MARS_IMAGES_FAIL";