export const GET_HOUSES = "GET_HOUSES";
export const GET_HOUSES_OK = "GET_HOUSES_OK";
export const GET_HOUSES_FAIL = "GET_HOUSES_FAIL";

export const GET_SINGLE_HOUSE = "GET_SINGLE_HOUSE"
export const GET_SINGLE_HOUSE_OK = "GET_SINGLE_HOUSE_OK"
export const GET_SINGLE_HOUSE_FAIL = "GET_SINGLE_HOUSE_FAIL"