export const GET_HOUSES = "GET_HOUSES";
export const GET_HOUSES_OK = "GET_HOUSES_OK";
export const GET_HOUSES_FAIL = "GET_HOUSES_FAIL";

export const GET_SINGLE_HOUSE = "GET_SINGLE_HOUSE";
export const GET_SINGLE_HOUSE_OK = "GET_SINGLE_HOUSE_OK";
export const GET_SINGLE_HOUSE_FAIL = "GET_SINGLE_HOUSE_FAIL";

export const POST_FAVORITES = "POST_FAVORITES";
export const POST_FAVORITES_OK = "POST_FAVORITES_OK";
export const POST_FAVORITES_FAIL = "POST_FAVORITES_FAIL";

export const GET_FAVORITES = "GET_FAVORITES";
export const GET_FAVORITES_OK = "GET_FAVORITES_OK";
export const GET_FAVORITES_FAIL = "GET_FAVORITES_FAIL";

export const GET_SINGLE_FAVORITE = "GET_SINGLE_FAVORITE";
export const GET_SINGLE_FAVORITE_OK = "GET_SINGLE_FAVORITE_OK";
export const GET_SINGLE_FAVORITE_FAIL = "GET_SINGLE_FAVORITE_FAIL";

export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const DELETE_FAVORITE_OK = "DELETE_FAVORITE_OK";
export const DELETE_FAVORITE_FAIL = "DELETE_FAVORITE_FAIL";

export const EDIT_FAV_HOUSE_INFO = "EDIT_FAV_HOUSE_INFO"
export const EDIT_FAV_HOUSE_INFO_OK = "EDIT_FAV_HOUSE_INFO_OK"
export const EDIT_FAV_HOUSE_INFO_FAIL = "EDIT_FAV_HOUSE_INFO_FAIL"